[package]
name = "solarlab-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
solarlab-domain = { path = "../domain" }
solarlab-hardware = { path = "../hardware" }
solarlab-physics = { path = "../physics" }
solarlab-runtime = { path = "../runtime" }

[lints]
workspace = true
